
package org.tnt.pt.service.costcalculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CostCalculator", targetNamespace = "com/erry/samacs/services/CostCalculator", wsdlLocation = "http://164.39.68.146:9090/smacs_sso/services/CostCalculator?wsdl")
public class CostCalculator_Service
    extends Service
{

    private final static URL COSTCALCULATOR_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://164.39.68.146:9090/smacs_sso/services/CostCalculator?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        COSTCALCULATOR_WSDL_LOCATION = url;
    }

    public CostCalculator_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CostCalculator_Service() {
        super(COSTCALCULATOR_WSDL_LOCATION, new QName("com/erry/samacs/services/CostCalculator", "CostCalculator"));
    }

    /**
     * 
     * @return
     *     returns CostCalculator
     */
    @WebEndpoint(name = "CostCalculatorPort")
    public CostCalculator getCostCalculatorPort() {
        return (CostCalculator)super.getPort(new QName("com/erry/samacs/services/CostCalculator", "CostCalculatorPort"), CostCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CostCalculator
     */
    @WebEndpoint(name = "CostCalculatorPort")
    public CostCalculator getCostCalculatorPort(WebServiceFeature... features) {
        return (CostCalculator)super.getPort(new QName("com/erry/samacs/services/CostCalculator", "CostCalculatorPort"), CostCalculator.class, features);
    }

}
